### ISSUE TITLE
还锁issue

### ISSUE THREAD

**Issue by Bottor-G** [srlss123/vtbmc#2]
# 原文

且待吾来考汝服务器之糟粕

- 为首者，乃尔之无礼，论他人之所游戏之物非尔应有之权，吾戏之不成吾何为
- 其次者，乃尔之心躁，仅欲他人已成之物，莫想亲己之为
- 其再者，乃尔之无术，以可动之水墨题“以一赞得一天之续”而引人耳目，非拔己物之内容以获他人之乐
- 而后者，乃尔之无德，且为坛主之其一，却滥用私权，非公非正
- 其末者，乃尔之素质之朴素，非高非低。曰可高，由他人之不暇，尔之不放；曰可低，由尔之言语轻柔，并无大碍

且补一点，当吾欲发此申明之时，拒吾之于门外，乃尔之气度之小也。

**且待吾声明一事：吾并非游于中原之人，但走于西域之地，既非一服之主，也非一服之相，欲击与吾之有关服务器者，皆落空也**

有一事乃吸睛也，何须吾入尔之Q群，是自觉不理？莫不是想煽风点火，借无知群友之力量，群起而攻吾也？

且末之言也，尔之有空锁我之issue，却不如览吾之项目列表，有几何尔可成乎？吾求技也，不求招也，莫不收招，求技固己？

知我之戏原，吾当你已阅吾之github主页，何不连坐吾之项目star者、关注者？

吾在此地立誓，若是汝可当真借自己之术胜吾与java或python，吾自认倒霉，于此地当面谢罪。窃他人之技乃上逆，若欲赢吾而盗之，非吾所认可之胜负。

吾仅怒汝之无礼，非欲争论不休，留此言，莫要再见！

# 翻译

接下来让我分析分析为什么你服务器不行

- 首先，你没有什么礼貌，对别人玩什么游戏做评价并不是你的权力，我玩原神不影响我人是个什么人
- 其次，你没有什么耐心，只想着伸手，没有想过自己去做点东西只想坐享其成
- 再者，你没什么技术，天天只会发那种“一个赞续费一天服务器”的视频来尝试给服务器吸引流量而不通过提升自己的技术而提升服务器的内容来吸引玩家
- 而后，你没有什么道德，当了苦力怕论坛的版主后滥用权力而不公正管理
- 最后，你的素质一般，不高也不低。说你有待提高，是因为别人不想理你你任然追着别人不放诋毁人家；说你有待降低，是因为你的攻击的话语实在不痛不痒，造不成什么实质性伤害

补充一点，当我想发这个声明的时候，发现你把我issue禁了，那我就再补充一点吧：你的气度太小了

**做个声明奥：我没玩过国内任何一个服务器，我一般只在国外的服务器里乱逛，不要把我当成国内一些服务器的服主或管理，想对和我有关的服务器进行攻击是无效的**

很亮眼的一件事，为什么非要我加你的qq群来跟你讨论呢，是自觉不再理？难不成是想要煽风点火，借助无知群友的力量，一起来攻击我？

最后再说一下吧，你有时间在这锁我的issue，你不如翻翻我的项目列表，看看有几个是你做的出来的？我是潜心搞技术的，没时间去玩你这种花招，不如收收你的花招，好好学学技术来的实在。

你知道了我玩原神，那就默认你看过我的github主页了，要不你把star我项目的人，关注我github账号的人，也一起攻击一下？

我发誓，如果你能真真正正靠你自己在java或者python上胜过我，我自认倒霉，当面认输谢罪。但是，偷窃他人的技术并不是一个可取的行为，如果你为了胜过我而偷取别人的技术，我是不认可的。

我只是想说说你的无礼罢了，并不想争论不休，留下这些话是想给你个劝告，没必要追着不放。

**Comment by srlss123** [comment]
1. 礼貌是区分人的，你这种隔壁服的人和我方处于敌对状态的没有必要对你礼貌（你对敌人会礼貌吗？笑）
2. 我有的是耐心，隔壁服那个叫deklly的腐竹都已经彻底跑路了，老子还是继续开着服务器，每个月续费1420
3. 我要真没技术，我服务器20人常驻，并且在多个百人服任职技术。我承认我的代码技术很差。但是做出一个好服务器绰绰有余。
4. 我任职苦力怕论坛版主没有对任何服务器进行不公平操作，谢谢。并且我现在也不是版主了，这个不由你评价，而是苦力怕论坛站长。他依然授予了我管理组荣誉勋章谢谢。
5. 对于敌对服务器和敌对组织/个人我从不手软。

**Comment by srlss123** [comment]
一个潜心搞技术的大佬，还没玩过国内服务器，你有这时间来怼我，不如好好看看你的代码怎么写。
你肯定是认识djelly4k，你就说你是隔壁服的呗 有那么难吗

【公告】
各位玩家，这里是服主 DJelly4K。
我很抱歉的来通知大家，祈愿服务器将于近期关闭。
感谢大家选择祈愿服务器，在过去的一年里，收到了大部分玩家的好评。但在今年，由于本人的个人原因，持续摆烂式管理服务器，无期限继续画大饼，导致服务器毁在了我自己手里，我并没有遵守承诺，完成我的计划。我不想再让玩家，让管理/客服每次期待都换来的失望，对于这件事，我深感抱歉与愧疚。
服务器将停止新玩家的进群通道，并在 1 月 26 日正式关闭服务器。届时玩家群将做解散处理，同时服务器数据将一并删除。玩家可以私下结为好友，继续交流。
如果你购买了本服务器会员，近期我会私聊你进行退款处理。
如果在祈愿关闭后你找不到合适的服务器游玩，我在这里推荐几个我认可的服务器：
1. 对于 粘液科技 的玩家，我推荐
① 未来城：https://www.mcbbs.net/thread-1392605-1-1.html
2. 对于 原版生存 的玩家，想要一个和谐的社区，我推荐
① HikariCraft 光服：https://klpbbs.com/thread-76338-1-1.html
② PlutoMC：https://www.bilibili.com/video/BV1MF411N7QV
感谢各位一路之上对服务器的支持，聚是一团火，散是满天星。我们有缘再见！

**Comment by srlss123** [comment]
老子用的所有东西不是开源就是付费的，从来不抄袭任何一个人的东西，傻逼op一个

**Comment by srlss123** [comment]
主要我很好奇，你不玩国内服务器还能知道我服务器哪儿差 笑死了
